// apps/sveltekit/src/lib/components/Button.svelte
<script lang="ts">
	let className = ''

	export {className as class}

	export let disabled: boolean | undefined = undefined
</script>

<button
	on:click
	{disabled}
	class={`${className} bg-surface-brand-2 focus:ring-foreground-accent active:duration-50 active:bg-surface-accent-1 relative rounded-lg px-4 py-8 text-5xl shadow transition duration-300 hover:brightness-125 focus:outline-none focus:ring-4 active:-translate-y-1 disabled:pointer-events-none disabled:opacity-50`}
	><slot /></button
>

// apps/nextjs/src/components/Button.tsx
import type {ButtonHTMLAttributes} from 'react'

import {cn} from '@/lib/utils'

type Props = ButtonHTMLAttributes<HTMLButtonElement>

export const Button = ({
	children,
	className,
	disabled,
	...restProps
}: Props) => (
	<button
		disabled={disabled}
		className={cn(
			className,
			'bg-surface-brand-2 active:duration-50 relative rounded-lg p-2 text-2xl shadow transition duration-300 hover:brightness-125 active:-translate-y-1 disabled:opacity-50',
			{'pointer-events-none select-none': disabled},
		)}
		{...restProps}
	>
		{children}
	</button>
)
