// apps/sveltekit/src/routes/munch-o-meter/Meter.svelte
<script lang="ts">
	import Cookie from '$lib/icons/Cookie.svelte'
	import type {EventHandler} from 'svelte/elements'
	import Button from './Button.svelte'
	import {fly} from 'svelte/transition'
	import {quintOut} from 'svelte/easing'

	const operations = [
		{label: '+ Add', value: 'increment'},
		{label: '- Reduce', value: 'decrement'},
		{label: '- Reset', value: 'reset'},
	]

	let count = 0

	const handleSubmit: EventHandler<SubmitEvent, HTMLFormElement> = (event) => {
		const operation = (event.submitter as HTMLButtonElement)?.value
		switch (operation) {
			case 'increment':
				count++
				break
			case 'decrement':
				count--
				break
			case 'reset':
				count = 0
				break
			default:
				break
		}
	}
</script>

<div class="grid grid-cols-2 place-items-center justify-center text-9xl">
	<Cookie class="w-32" />
	<div class="grid h-full w-full items-center justify-center">
		{#key count}
			<span
				class="count"
				transition:fly={{
					delay: 250,
					duration: 300,
					y: 100,
					easing: quintOut,
				}}
			>
				{count}
			</span>
		{/key}
	</div>
</div>

<form on:submit|preventDefault={handleSubmit} class="grid grid-cols-3 gap-4">
	{#each operations as { label, value }}
		<Button disabled={value === 'decrement' && count <= 0} {value}
			>{label}</Button
		>
	{/each}
</form>

<section class="flex gap-4 text-xl">
	<div>Mood 🎅:</div>
	<div>
		{#if count === 0}
			hangry 😡
		{:else if count > 10}
			stuffed 😋
		{:else}
			jolly 😁
		{/if}
	</div>
</section>

<style>
	.count {
		grid-area: 1/1;
	}
</style>

// apps/nextjs/src/app/munch-o-meter/Meter.tsx
'use client'

import {FormEventHandler, useState} from 'react'

import {Button} from '@/components/Button'
import {Cookie} from './Cookie'

const operations = [
	{label: '+ Add', value: 'increment'},
	{label: '- Reduce', value: 'decrement'},
	{label: '- Reset', value: 'reset'},
]

export const Meter = () => {
	const [count, setCount] = useState(0)
	const handleSubmit: FormEventHandler<HTMLFormElement> = (event) => {
		event.preventDefault()
		// the event does have a submitter!
		// @ts-ignore
		const submitButton: HTMLButtonElement = event.nativeEvent.submitter
		const operation = submitButton?.value

		switch (operation) {
			case 'increment':
				setCount((c) => c + 1)
				break
			case 'decrement':
				setCount((c) => c - 1)
				break
			case 'reset':
				setCount(0)
				break
			default:
				break
		}
	}
	return (
		<>
			<div className="grid grid-cols-2 place-items-center justify-center text-9xl">
				<Cookie className="w-32" />
				<div>{count}</div>
			</div>

			<form onSubmit={handleSubmit} className="grid grid-cols-3 gap-4">
				{operations.map(({label, value}) => (
					<Button
						name="operation"
						key={label}
						disabled={value === 'decrement' && count <= 0}
						value={value}
					>
						{label}
					</Button>
				))}
			</form>

			<section className="flex items-center justify-center gap-4 text-2xl">
				<div>Mood 🎅:</div>
				<div>
					{count === 0 ? (
						<>hangry 😡</>
					) : count > 10 ? (
						<>stuffed 😋</>
					) : (
						<>jolly 😁</>
					)}
				</div>
			</section>
		</>
	)
}
