// apps/nextjs/src/app/the-list/page.tsx
import {NaughtyOrNiceTracker} from './NaughtyOrNiceTracker'

type Props = {
	searchParams?: {
		query?: string
		status?: string
	}
}
const TheList = ({searchParams}: Props) => {
	const query = searchParams?.query
	const status = searchParams?.status

	return (
		<main className="content-grid grow gap-y-4 lg:gap-y-8">
			<h1 className="text-4xl font-bold lg:text-6xl">
				Naughty or Nice Tracker
			</h1>

			<NaughtyOrNiceTracker query={query} status={status} />
		</main>
	)
}

export default TheList

// apps/sveltekit/src/routes/the-list/+page.svelte
<script>
	import NaughtyOrNiceTracker from './NaughtyOrNiceTracker.svelte'

	export let data
</script>

<main class="content-grid grow gap-y-4 lg:gap-y-8">
	<h1 class="text-4xl font-bold lg:text-6xl">Naughty or Nice Tracker</h1>

	<NaughtyOrNiceTracker kids={data.kids} />
</main>

<style>
	h1 {
		view-transition-name: tracker-header;
	}

	/* Exit transition */
	:global(::view-transition-old(tracker-header)):only-child {
		animation: 300ms ease-out both fade-out-to-left;
	}

	/* Entry transition */
	:global(::view-transition-new(tracker-header)):only-child {
		animation: 300ms ease-out both slide-from-right;
	}
</style>
